[Project Addition]: Almond Varieties Image Classification
abhisheks008/DL-Simplified pull request #758
Opened 2024-06-07 15:18 UTC by jeet-Abhi123

# Pull Request for DL-Simplified 💡

## Issue Title : 

- **Info about the related issue (Aim of the project)** : 
- **Name:** 
- **GitHub ID:** 
- **Email ID:** 
- **Idenitfy yourself: (Mention in which program you are contributing in. )** 

Closes: #740 

### Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made

I have implemented the InceptionV3, VGG19 & ResNet50 models with proper image classification techniques.

## Type of change ☑️

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2024-06-07 17:43 UTC, abhisheks008 requested changes
Need to do some EDA before directly implementing the models. Add the EDA results inside the Images folder.

2024-06-07 17:43 UTC, abhisheks008 commented on Almond Varieties Image Classification/README.md
> +###Accuracy Results
Typing mistake.

2024-06-07 19:01 UTC, jeet-Abhi123 commented
@abhisheks008  
Made the necessary changes.

2024-06-09 04:27 UTC, abhisheks008 approved these changes
Approved @jeet-Abhi123

2024-06-09 04:28 UTC, merged